import type { TitanSchema } from "@titanbase/core";
import { postgresCreateTableSql, postgresForeignKeySql, postgresIndexSql, postgresLiteral, qualifiedPostgresName, quotePostgresIdentifier } from "./format";

export interface PostgresExportResult {
  sql: string;
  warnings: string[];
}

// ---------------------------------------------------------------------------
// exportPostgres — generates DDL SQL from a TitanSchema.
//
// Supports:
// - CREATE SCHEMA (if any table uses table.schema)
// - CREATE TYPE for enums
// - CREATE TABLE with columns, NOT NULL, UNIQUE, DEFAULT, PRIMARY KEY
// - Foreign keys via ALTER TABLE
// - Indexes with method, partial WHERE, and uniqueness
// - COMMENT ON for tables, columns, indexes, constraints, and types
//
// Guarantees:
// - Deterministic output (same schema → same SQL)
// - Safe identifier quoting
// - Warnings for unsupported types (falls back to text)
// - Never crashes on invalid schemas (produces best-effort output)
// ---------------------------------------------------------------------------

export function exportPostgres(schema: TitanSchema): PostgresExportResult {
  const warnings: string[] = [];

  if (schema.dialect !== "postgres" && schema.dialect !== "generic") {
    warnings.push(`Schema dialect "${schema.dialect}" may contain types PostgreSQL does not support.`);
  }

  const statements: string[] = ["-- Generated by Titanbase", ""];

  // Collect schemas used by tables
  const schemas = new Set(schema.tables.map((t) => t.schema).filter((s): s is string => Boolean(s)));
  for (const schemaName of [...schemas].sort()) {
    statements.push(`CREATE SCHEMA IF NOT EXISTS ${quotePostgresIdentifier(schemaName)};`);
  }
  if (schemas.size > 0) statements.push("");

  // Enums
  for (const item of schema.enums) {
    statements.push(`CREATE TYPE ${quotePostgresIdentifier(item.name)} AS ENUM (${item.values.map(postgresLiteral).join(", ")});`);
    if (item.description) statements.push(`COMMENT ON TYPE ${quotePostgresIdentifier(item.name)} IS ${postgresLiteral(item.description)};`);
    statements.push("");
  }

  // Tables
  const tableById = new Map(schema.tables.map((t) => [t.id, t]));
  for (const table of schema.tables) {
    const createTable = postgresCreateTableSql(table, schema.enums);
    statements.push(createTable.sql);
    warnings.push(...createTable.warnings);

    if (table.description) {
      statements.push(`COMMENT ON TABLE ${qualifiedPostgresName(table.schema, table.name)} IS ${postgresLiteral(table.description)};`);
    }

    for (const column of table.columns) {
      if (column.description) {
        statements.push(`COMMENT ON COLUMN ${qualifiedPostgresName(table.schema, table.name)}.${quotePostgresIdentifier(column.name)} IS ${postgresLiteral(column.description)};`);
      }
    }

    // Indexes
    for (const index of table.indexes) {
      const formatted = postgresIndexSql(table, index);
      if (!formatted.sql) { if (formatted.warning) warnings.push(formatted.warning); continue; }
      statements.push(formatted.sql);
      if (formatted.warning) warnings.push(formatted.warning);

      if (index.description) {
        statements.push(`COMMENT ON INDEX ${qualifiedPostgresName(table.schema, index.name)} IS ${postgresLiteral(index.description)};`);
      }
    }

    statements.push("");
  }

  // Foreign keys
  for (const relation of schema.relations) {
    const fromTable = tableById.get(relation.from.table);
    const toTable = tableById.get(relation.to.table);

    if (!fromTable || !toTable) {
      warnings.push(`Relation "${relation.name}": skipped because a referenced table is missing.`);
      continue;
    }

    const formatted = postgresForeignKeySql(relation, fromTable, toTable);
    if (!formatted.sql) { if (formatted.warning) warnings.push(formatted.warning); continue; }
    statements.push(formatted.sql);

    if (relation.description) {
      statements.push(`COMMENT ON CONSTRAINT ${quotePostgresIdentifier(relation.name)} ON ${qualifiedPostgresName(fromTable.schema, fromTable.name)} IS ${postgresLiteral(relation.description)};`);
    }
  }

  return { sql: `${statements.join("\n").trim()}\n`, warnings };
}

export { generatePostgresMigrationDraft, type GeneratePostgresMigrationDraftOptions, type MigrationDraftResult, type MigrationDraftStatement, type MigrationDraftWarning } from "./migration-draft";
