import { describe, expect, it } from "vitest";
import { createEmptySchema, type TitanSchema } from "@titanbase/core";
import ecommerce from "../../../examples/ecommerce/ecommerce.titan.json";
import { exportDrizzle } from "../src";
import { loadExampleSchemas } from "../../../test-utils/example-schemas";

const schema = ecommerce as TitanSchema;

describe("Drizzle exporter", () => {
  it.each(loadExampleSchemas())("exports $name deterministically", ({ schema: example }) => {
    const first = exportDrizzle(example);
    const second = exportDrizzle(example);
    expect(first.files[0]?.path).toBe("schema.ts");
    expect(first.files[0]?.content).toContain('from "drizzle-orm/pg-core"');
    expect(first).toEqual(second);
  });

  it("exports the Ecommerce example", () => {
    const result = exportDrizzle(schema);
    const content = result.files[0]?.content ?? "";
    expect(result.files[0]?.path).toBe("schema.ts");
    expect(content).toContain('from "drizzle-orm/pg-core"');
    expect(content).toContain("pgTable");
    expect(content).toContain("export const");
  });

  it("is deterministic", () => {
    expect(exportDrizzle(schema)).toEqual(exportDrizzle(schema));
  });

  it("falls back with warnings for unsupported features", () => {
    const modified = structuredClone(schema);
    modified.tables[0]!.columns[0]!.type = "vector";
    modified.tables[0]!.columns[0]!.default = "custom_database_function()";
    modified.tables[0]!.indexes.push({ id: "partial", name: "partial", table: modified.tables[0]!.id, columns: [modified.tables[0]!.columns[0]!.id], unique: false, method: "gin", where: "id IS NOT NULL" });
    const result = exportDrizzle(modified);
    expect(result.files[0]?.content).toContain("text(");
    expect(result.warnings.length).toBeGreaterThan(0);
  });

  it("maps reserved, unsafe, and duplicate identifiers", () => {
    const modified = structuredClone(schema);
    modified.tables[0]!.name = "class";
    modified.tables[1]!.name = "class!";
    modified.tables[0]!.columns[0]!.name = "default";
    modified.tables[0]!.columns[1]!.name = "order-id";
    const content = exportDrizzle(modified).files[0]?.content ?? "";
    expect(content).toContain('export const class_ = pgTable("class"');
    expect(content).toContain('export const class_2 = pgTable("class!"');
    expect(content).toContain('default_: uuid("default")');
    expect(content).toContain('orderId: text("order-id")');
  });

  it("orders dependencies, warns for cycles, and supports empty schemas", () => {
    const reversed = structuredClone(schema);
    reversed.tables.reverse();
    const ordered = exportDrizzle(reversed).files[0]?.content ?? "";
    const customersPosition = ordered.indexOf('pgTable("customers"');
    const ordersPosition = ordered.indexOf('pgTable("orders"');
    expect(customersPosition).toBeLessThan(ordersPosition);

    const cyclic = structuredClone(schema);
    cyclic.relations.push({ id: "customers_orders", name: "customers_orders", from: { table: "customers", columns: ["customers.id"] }, to: { table: "orders", columns: ["orders.id"] }, cardinality: "one-to-one" });
    const cycleResult = exportDrizzle(cyclic);
    expect(cycleResult.warnings.some((warning) => warning.code === "DRIZZLE_RELATION_CYCLE")).toBe(true);
    expect(cycleResult).toEqual(exportDrizzle(cyclic));

    const empty = exportDrizzle(createEmptySchema()).files[0]?.content ?? "";
    expect(empty).toContain("Generated by Titanbase");
  });
});
